import type { Metadata } from "next"
import { ProductListing } from "@/components/product-listing"
import { getProductCatalog } from "@/services/catalog.service"

// Statically generated by default (no dynamic input on this route), which
// would otherwise bake the Firestore product list in at build time and
// never pick up newly-approved products without a full redeploy.
export const revalidate = 60

export const metadata: Metadata = {
  title: "Shop All | YashWorld",
  description: "Discover premium products from every category at YashWorld.",
}

export default async function ProductsPage() {
  const products = await getProductCatalog()

  return (
    <main className="min-h-screen bg-white">

      <section className="mx-auto max-w-7xl px-6 py-14">

        <div className="text-center">

          <span className="text-green-600 font-semibold uppercase tracking-[0.25em]">
            YashWorld Store
          </span>

          <h1 className="mt-4 text-5xl font-bold text-gray-900">
            Shop All Products
          </h1>

          <p className="mx-auto mt-5 max-w-2xl text-lg text-gray-500">
            Explore our complete collection of indoor plants, outdoor plants,
            pots, seeds, fertilizers and gardening essentials —
            everything for your plant journey in one place.
          </p>

          <div className="mt-8 flex items-center justify-center gap-4">

            <div className="rounded-xl bg-green-50 px-6 py-4 shadow-sm">
              <h3 className="text-3xl font-bold text-green-700">
                {products.length}
              </h3>
              <p className="text-gray-600">
                Products
              </p>
            </div>

            <div className="rounded-xl bg-green-50 px-6 py-4 shadow-sm">
              <h3 className="text-3xl font-bold text-green-700">
                6
              </h3>
              <p className="text-gray-600">
                Categories
              </p>
            </div>

          </div>

        </div>

        <div className="mt-14">
          <ProductListing products={products} />
        </div>

      </section>

    </main>
  )
}